
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRootPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author felip
 */
public class VentanaHistoria extends javax.swing.JFrame {

  JFrame ventanaPrincipal;
  Elemento elemento;

  /**
   * Creates new form VentanaHistoria
   *
   * @param ventanaPrincipal
   * @param elemento
   */
  public VentanaHistoria(JFrame ventanaPrincipal, Elemento elemento) {
    this.ventanaPrincipal = ventanaPrincipal;
    this.elemento = elemento;

    initComponents();

    getContentPane().setBackground(Color.BLACK);
    this.getRootPane().setWindowDecorationStyle(JRootPane.NONE);

    ImageIcon imagen;
    File f = new File(elemento.getNombre() + ".gif");
    if (f.exists() && !f.isDirectory()) {
      imagen = new ImageIcon(new ImageIcon(elemento.getNombre() + ".gif").getImage().getScaledInstance(278, 210, Image.SCALE_DEFAULT));
    } else {
      imagen = new ImageIcon(new ImageIcon(elemento.getNombre() + ".jpg").getImage().getScaledInstance(278, 210, Image.SCALE_DEFAULT));
    }
    this.imagen.setIcon(imagen);
    this.jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
    this.informacionTexto.setText(elemento.getHistoria());
    this.informacionTexto.setLineWrap(true);
    this.informacionTexto.setWrapStyleWord(true);
    this.nombreEtiqueta.setText("History of " + elemento.getNombre());
    this.setVisible(true);

    link1.setText(elemento.getLinks()[0]);
    link1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    link1.addMouseListener(new MouseAdapter() {
      public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() > 0) {
          if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
              JLabel etiqueta = (JLabel) e.getComponent();
              URI uri = new URI(etiqueta.getText());
              desktop.browse(uri);
            } catch (IOException | URISyntaxException ex) {
            }
          }
        }
      }
    });
    
    link2.setText(elemento.getLinks()[1]);
    link2.addMouseListener(link1.getMouseListeners()[0]);
    link2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    link3.setText(elemento.getLinks()[2]);
    link3.addMouseListener(link1.getMouseListeners()[0]);
    link3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    //link.setLocation(40, 40);
    

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    informacionTexto = new javax.swing.JTextArea();
    imagen = new javax.swing.JLabel();
    botonCerrar = new javax.swing.JButton();
    nombreEtiqueta = new javax.swing.JLabel();
    link1 = new javax.swing.JLabel();
    link2 = new javax.swing.JLabel();
    link3 = new javax.swing.JLabel();
    link4 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setUndecorated(true);

    informacionTexto.setEditable(false);
    informacionTexto.setBackground(new java.awt.Color(0, 0, 0));
    informacionTexto.setColumns(20);
    informacionTexto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
    informacionTexto.setRows(5);
    informacionTexto.setBorder(null);
    informacionTexto.setCaretColor(new java.awt.Color(0, 0, 0));
    informacionTexto.setDisabledTextColor(new java.awt.Color(153, 153, 153));
    informacionTexto.setEnabled(false);
    jScrollPane1.setViewportView(informacionTexto);

    botonCerrar.setBackground(new java.awt.Color(153, 0, 0));
    botonCerrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
    botonCerrar.setForeground(new java.awt.Color(0, 0, 0));
    botonCerrar.setLabel("X");
    botonCerrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
    botonCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonCerrarActionPerformed(evt);
      }
    });

    nombreEtiqueta.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
    nombreEtiqueta.setForeground(new java.awt.Color(204, 204, 204));
    nombreEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    nombreEtiqueta.setText("nombreElem");

    link1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    link1.setText("link");

    link2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    link2.setText("link");

    link3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    link3.setText("link");

    link4.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
    link4.setText("Links with more information about the element: ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(20, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(link1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(link2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(link3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(link4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
            .addGap(26, 26, 26))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
          .addComponent(nombreEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(57, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(botonCerrar)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(nombreEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(282, 282, 282))
          .addGroup(layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)))
        .addComponent(link4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(link1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(link2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(6, 6, 6)
        .addComponent(link3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(30, 30, 30))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
    this.dispose();
    this.ventanaPrincipal.setVisible(true);
  }//GEN-LAST:event_botonCerrarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton botonCerrar;
  private javax.swing.JLabel imagen;
  private javax.swing.JTextArea informacionTexto;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel link1;
  private javax.swing.JLabel link2;
  private javax.swing.JLabel link3;
  private javax.swing.JLabel link4;
  private javax.swing.JLabel nombreEtiqueta;
  // End of variables declaration//GEN-END:variables
}
